version: '3.9'

services:
  web:
    build: .
    command: python winery/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
  # django:
  #   image: winery-manager:0.0.1
  #   build: .
  #   ports:
  #     - "8000:8000"