# Generated by Django 5.0.3 on 2024-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0003_alter_product_expirery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
