# Generated by Django 5.0.3 on 2024-04-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0005_sale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="product_id",
            new_name="product",
        ),
    ]
