# Generated by Django 5.0.4 on 2024-05-12 11:51

import products_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_product_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(validators=[products_app.models.validate_positive]),
        ),
    ]
