# Generated by Django 5.0.4 on 2024-05-12 11:57

import products_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(validators=[products_app.models.validate_positive]),
        ),
    ]
